apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ns1
spec:
  selector:
    matchLabels:
      app: nginx-ns1
  template:
    metadata:
      labels:
        app: nginx-ns1
    spec:
      containers:
      - image: nginx
        name: nginx-ns1
        ports:
        - containerPort: 80
        resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ns1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ns1.wmar.io
    external-dns.alpha.kubernetes.io/ttl: "1"
spec:
  externalIPs:
  - 98.190.75.21
  selector:
    app: nginx-ns1
  type: LoadBalancer
  ports:
    - nodePort: 30081
      protocol: TCP
      port: 80
      targetPort: 80