apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cox-sp
spec:
  selector:
    matchLabels:
      app: nginx-cox-sp
  template:
    metadata:
      labels:
        app: nginx-cox-sp
    spec:
      containers:
      - image: nginx
        name: nginx-cox-sp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cox-sp
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cox-sp.marchesi.dev
    external-dns.alpha.kubernetes.io/ttl: "0"
spec:
  selector:
    app: nginx-cox-sp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
